# Generated by Django 5.1.11 on 2025-08-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
