# Generated by Django 5.1.11 on 2025-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('engineer', 'Engineer')], max_length=100, verbose_name='Employee Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas')], max_length=100, verbose_name='Work Domain'),
        ),
    ]
