# Generated by Django 5.1.11 on 2025-09-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employee_level_user_work_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Choice Name (Uzbek Latin)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Uzbek Cyrillic)')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Russian)')),
            ],
        ),
        migrations.CreateModel(
            name='GTFStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Choice Name (Uzbek Latin)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Uzbek Cyrillic)')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Russian)')),
            ],
        ),
        migrations.CreateModel(
            name='PositionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Choice Name (Uzbek Latin)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Uzbek Cyrillic)')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Choice Name (Russian)')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branchstaff', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='gtf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gtfstaff', verbose_name='GTF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.positionstaff', verbose_name='Position'),
        ),
    ]
