# Generated by Django 5.1.11 on 2025-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_branchstaff_gtfstaff_remove_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionstaff',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas')], max_length=100, verbose_name='Work Domain'),
        ),
    ]
