# Generated by Django 5.1.11 on 2025-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_branchstaff_gtfstaff_positionstaff_alter_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
