# Generated by Django 5.1.11 on 2025-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_positionstaff_work_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionstaff',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas'), ('both', 'Both')], max_length=100, verbose_name='Work Domain'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas'), ('both', 'Both')], max_length=100, verbose_name='Work Domain'),
        ),
    ]
