# Generated by Django 5.1.11 on 2025-08-29 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions_count',
            field=models.PositiveIntegerField(default=30, help_text='Number of random questions to show from the pool', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Questions Count'),
        ),
    ]
