# Generated by Django 5.1.11 on 2025-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='session_questions',
            field=models.ManyToManyField(related_name='sessions', through='surveys.SessionQuestion', to='surveys.question'),
        ),
    ]
