# Generated by Django 5.1.11 on 2025-08-29 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveysession_session_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='retake_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_retakes', to=settings.AUTH_USER_MODEL, verbose_name='Retake Granted By'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='retake_reason',
            field=models.TextField(blank=True, help_text='Reason for granting retake permission', verbose_name='Retake Reason'),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='can_retake',
            field=models.BooleanField(default=False, help_text='Moderator granted permission for retake', verbose_name='Can Retake'),
        ),
    ]
