# Generated by Django 5.1.11 on 2025-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveysession_retake_granted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas')], help_text='Work domain this question is relevant for. Leave blank for all domains.', max_length=100, verbose_name='Work Domain'),
        ),
    ]
