# Generated by Django 5.1.11 on 2025-09-13 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_question_work_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEmployeeLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_level', models.CharField(choices=[('junior', 'Junior'), ('engineer', 'Engineer')], max_length=100, verbose_name='Employee Level')),
                ('questions_count', models.PositiveIntegerField(default=30, help_text='Number of questions for this employee level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Questions Count')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_level_configs', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Employee Level Config',
                'verbose_name_plural': 'Survey Employee Level Configs',
                'ordering': ['survey', 'employee_level'],
                'unique_together': {('survey', 'employee_level')},
            },
        ),
    ]
