# Generated by Django 5.1.11 on 2025-09-13 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveyemployeelevelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('safety_logic_psychology', 'Safety, Logic (IQ), Psychology'), ('other', 'Other')], default='other', help_text='Question category for percentage distribution', max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='other_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Percentage of questions from Other category', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Other Category Percentage'),
        ),
        migrations.AddField(
            model_name='survey',
            name='safety_logic_psychology_percentage',
            field=models.PositiveIntegerField(default=70, help_text='Percentage of questions from Safety, Logic (IQ), Psychology category', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Safety, Logic, Psychology Percentage'),
        ),
    ]
