# Generated by Django 5.1.11 on 2025-09-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_question_category_survey_other_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='certificate_order',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing order number for certificate identification', null=True, verbose_name='Certificate Order Number'),
        ),
    ]
