# Generated by Django 5.1.11 on 2025-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveysession_certificate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='work_domain',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('lpg_gas', 'LPG Gas'), ('both', 'Both')], help_text='Work domain this question is relevant for. Leave blank for all domains.', max_length=100, verbose_name='Work Domain'),
        ),
    ]
