# Generated by Django 5.1.11 on 2025-10-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_surveysession_face_reference_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField(help_text='Sequential chunk number', verbose_name='Chunk Number')),
                ('chunk_file', models.FileField(upload_to='video_chunks/%Y/%m/%d/', verbose_name='Chunk File')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes', verbose_name='File Size')),
                ('duration_seconds', models.FloatField(help_text='Duration in seconds', verbose_name='Duration')),
                ('start_time', models.FloatField(help_text='Start time in seconds from session start', verbose_name='Start Time')),
                ('end_time', models.FloatField(help_text='End time in seconds from session start', verbose_name='End Time')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('has_audio', models.BooleanField(default=True, verbose_name='Has Audio')),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1280x720', max_length=20, verbose_name='Resolution')),
                ('fps', models.IntegerField(blank=True, null=True, verbose_name='FPS')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chunks', to='surveys.surveysession')),
            ],
            options={
                'verbose_name': 'Video Chunk',
                'verbose_name_plural': 'Video Chunks',
                'ordering': ['session', 'chunk_number'],
                'indexes': [models.Index(fields=['session', 'chunk_number'], name='surveys_vid_session_dbe2f2_idx')],
                'unique_together': {('session', 'chunk_number')},
            },
        ),
    ]
