# Generated by Django 5.1.11 on 2025-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_videochunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='playlist_file',
            field=models.FileField(blank=True, help_text='M3U8 HLS playlist for video chunks', null=True, upload_to='session_recordings/playlists/%Y/%m/%d/', verbose_name='HLS Playlist File'),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='video_file',
            field=models.FileField(blank=True, help_text='Full merged video file (optional, use playlist_file for HLS)', null=True, upload_to='session_recordings/%Y/%m/%d/', verbose_name='Video File'),
        ),
    ]
